# assignment

vara = (30*2)
print("vara =", vara)
print("type of vara", type(vara))
print("-----")
vara = (30)
print("vara =", vara)
print("type of vara", type(vara))
print("-----")
vara = (30, 60)
print("vara =", vara)
print("type of vara", type(vara))
print("-----")
vara = (30,)
print("vara =", vara)
print("type of vara", type(vara))
print("-----")
vara = 30,
print("vara =", vara)
print("type of vara", type(vara))
print("-----")
vara = tuple((30,))
print("vara =", vara)
print("type of vara", type(vara))
